version: "3.8"
services:
  mysql:
    container_name: crud_mysql
    image: mysql:latest
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql;
      - ./docker/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crud_mysql
      MYSQL_PASSWROD: password
    ports:
      - "3301:3306"